version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "saurbhc"
      - "JBWilkie"
    open-pull-requests-limit: 5
    labels:
      - "github-actions-updates"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # For all packages, ignore all major updates
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    reviewers:
      - "saurbhc"
      - "JBWilkie"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
