[tool.poetry]
name = "darwin-py"
version = "0.8.9" # update this when you change the version - See: https://peps.python.org/pep-0440/
description = "Library and command line interface for darwin.v7labs.com"
homepage = "https://docs.v7labs.com/reference/getting-started-2"
documentation = "https://darwin-py-sdk.v7labs.com/index.html"
repository = "https://github.com/v7labs/darwin-py"
authors = ["V7 <info@v7labs.com>"]
readme = "README.md"
license = "MIT"

keywords = []
classifiers = ["Programming Language :: Python :: 3", "License :: OSI Approved :: MIT License"]

packages = [
    { include = "darwin" },
]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.11"
argcomplete = "^2.0.0"
humanize = "^4.4.0"
pillow = "^9.4.0"
pyyaml = ">=5.1"
requests = "^2.28.1"
rich = "^13.0.1"
dataclasses = {markers = "python_version < \"3.7\"", version = "^0.8"}
upolygon = "0.1.8"
jsonschema = ">=4.0.0"
deprecation = "^2.1.0"
pydantic = "^1.10.4"
orjson = "^3.8.5"
numpy = "<=1.23.0"
toml = "^0.10.2"
nibabel = {version = "^5.0.0", extras = ["medical"]}
connected-components-3d = {version = "^3.10.3", extras = ["medical"]}
scikit-learn = {version = "^1.2.0", extras = ["ml", "test"]}
torch = {version = "^1.13.1", extras = ["ml"]}
torchvision = {version = "^0.14.1", extras = ["ml"]}
black = {version = "^22.12.0", extras = ["dev"]}
isort = {version = "^5.11.4", extras = ["dev"]}
flake8 = {version = "^6.0.0", extras = ["dev"], python = ">=3.8.1,<3.11"}
mypy = {version = "^0.991", extras = ["dev"]}
responses = {version = "^0.22.0", extras = ["test", "dev"]}
pytest = {version = "^7.2.1", extras = ["test", "dev"]}
pytest-describe = {version = "^2.0.1", extras = ["test", "dev"]}
flake8-pyproject = {version = "^1.2.2", extras = ["test", "dev"], python = ">=3.8.1,<3.11"}
debugpy = {version = "^1.6.5", extras = ["dev"]}

[tool.poetry.extras]
dev = ["black", "isort", "flake8", "mypy", "debugpy", "responses", "pytest", "pytest-describe", "flake8-pyproject"]
test = ["responses", "pytest", "pytest-describe", "flake8-pyproject"]
ml = ["torch", "torchvision", "scikit-learn"]
medical = ["nibabel", "connected-components-3d"]

[tool.poetry.scripts]
darwin = "darwin.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

#  TOOL SETTINGS

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
disallow_any_unimported = true
disallow_any_expr = false
disallow_any_decorated = false
disallow_any_explicit = true
disallow_any_generics = false
disallow_subclassing_any = true
python_version = "3.10"
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_return_any = false
warn_unreachable = true
pretty = true

[tool.black]
line-length = 160

[tool.flake8]
max-line-length = 160