name: "Update Linear Labels"

permissions:
  contents: read

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  update-linear:
    if: github.ref_name != 'master' && !github.event.pull_request.head.repo.fork
    name: Update Linear
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: v7labs/update-linear-labels-action@0d527ddba6f2f0e0c28c3ec5c8a26767caf13ee3 # v1
        with:
          label_name: "DarwinPy"
          branch_name: "${{ github.head_ref }}"
          linear_token: "${{ secrets.LINEAR_TOKEN }}"
          error_exit_code: 0
