name: merge_to_master
run-name: Merge to master

on:
  push:
    branches:
      - master
  workflow_call:

permissions:
  contents: read
  id-token: write # Necessary for the generate documentation job 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run_tests:
    name: Run tests
    uses: ./.github/workflows/JOB_tests.yml

  documentation:
    name: Documentation
    uses: ./.github/workflows/JOB_generate_documentation.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read

  warn_on_fail:
    needs: [run_tests, documentation]
    if: ${{ failure() }}
    name: Slack message us on fail
    uses: ./.github/workflows/JOB_slack_message.yml
    secrets: inherit
    with:
      at_team: true
      icon: ':warning:'
      message: 'Master is failing after a push event, please review at ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}'

  success:
    needs: [run_tests, documentation]
    if: ${{ success() }}
    name: Success
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Set branch status to success
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success'
            })