name: lint
run-name: Check linting

on:
  workflow_call:
    inputs:
      files:
        type: string
        description: "Files to lint"
        required: true

permissions:
  contents: read

jobs:
  lint:
    if: ${{ inputs.files != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - name: Check out source repository
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

    - name: Set up Python environment
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: "3.10"

    - name: Show filenames
      run: echo ${{ inputs.files }}

    - name: Ruff Lint
      shell: bash
      run: bash ${{ github.workspace }}/deploy/format_lint.sh lint ${{ inputs.files }}
