name: format
run-name: Format

on:
  workflow_call:
    inputs:
      files:
        description: "Files to check formatting of"
        required: true
        type: string

permissions:
  contents: read

jobs:
  format:
    if: ${{ inputs.files != '' }}
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - name: Check out source repository
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

    - name: Set up Python environment
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: "3.11"

    - name: Show filenames
      run: echo ${{ inputs.files }}

    - name: Black check
      shell: bash
      run: bash ${{ github.workspace }}/deploy/format_lint.sh format ${{ inputs.files }}

