name: slack-notify
run-name: Slack Notify

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK:
        required: true
    inputs:
      message:
        type: string
        description: 'The message to send'
        required: true

      icon:
        type: string
        description: 'The icon to use'
        required: false
        default: ':snake:'

      at_team:
        type: boolean
        description: 'Whether to hail the developers in the message'
        required: false
        default: false

env:
  PREFIX: ${{ vars.SLACK_TEAM_TAG }}

permissions:
  contents: read

jobs:
  slack-notify:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Require secrets inherit
        run: |
          if [ -z "${{ secrets.SLACK_WEBHOOK }}" ]; then
            echo "Missing secret: SLACK_WEBHOOK"
            echo "You must call this reusable flow with secrets inherited."
            exit 1
          fi

      - name: Send Slack Notification
        run: |
          if [ ${{ inputs.at_team }} = true ]; then
            PAYLOAD=$(cat <<EOF
            {
              "channel": "#${{ vars.SLACK_CHANNEL }}",
              "username": "${{ vars.SLACK_USERNAME }}",
              "text": "${{ inputs.message }}",
              "icon_emoji": "${{ inputs.icon || vars.SLACK_ICON }}"
            }
          EOF
          )
          else
          PAYLOAD=$(cat <<EOF
          {
            "channel": "#${{ vars.SLACK_CHANNEL }}",
            "username": "${{ vars.SLACK_USERNAME }}",
            "text": "${{ env.PREFIX }}${{ inputs.message }}",
            "icon_emoji": "${{ inputs.icon || vars.SLACK_ICON }}"
          }
          EOF
          )
          fi
          curl -X POST --data-urlencode "payload=$PAYLOAD" ${{ secrets.SLACK_WEBHOOK }}
