name: format
run-name: Format

on:
  workflow_call:
    inputs:
      files:
        description: "Files to check formatting of"
        required: true
        type: string

permissions:
  contents: read

jobs:
  format:
    if: ${{ inputs.files != '' }}
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - name: Check out source repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Python environment
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: "3.11"

    - name: Show filenames
      run: echo ${{ inputs.files }}

    - name: Black check
      shell: bash
      run: bash ${{ github.workspace }}/deploy/format_lint.sh format ${{ inputs.files }}

