name: get_changed_files
run-name: Get changed get_changed_files

on:
  workflow_call:
    outputs:
      changed_files:
        description: "Changed files"
        value: ${{ jobs.get_changed_files.outputs.changed_files }}
      python_changed_files:
        description: "Changed python files"
        value: ${{ jobs.get_changed_files.outputs.python_changed_files }}
      yaml_changed_files:
        description: "Changed yaml files"
        value: ${{ jobs.get_changed_files.outputs.yaml_changed_files }}
      json_changed_files:
        description: "Changed json files"
        value: ${{ jobs.get_changed_files.outputs.json_changed_files }}

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  get_changed_files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed_files.outputs.changed_files }}
      python_changed_files: ${{ steps.changed_python_files.outputs.python_changed_files }}
      yaml_changed_files: ${{ steps.changed_yaml_files.outputs.yaml_changed_files }}
      json_changed_files: ${{ steps.changed_json_files.outputs.json_changed_files }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref }}
      - name: Get changed files
        id: changed_files
        shell: bash
        run: |
          changed_files=`gh pr diff ${{ github.event.number }} --name-only | xargs`
          echo "Changed files: $changed_files"
          echo "changed_files=$changed_files" >> $GITHUB_OUTPUT
      - name: Get changed python files
        id: changed_python_files
        shell: bash
        run: |
          changed_files=`python3 ${{ github.workspace }}/deploy/_filter_files.py py ${{ steps.changed_files.outputs.changed_files }}`
          echo "Changed python files: $changed_files"
          echo "python_changed_files=$changed_files" >> $GITHUB_OUTPUT
      - name: Get changed yaml files
        id: changed_yaml_files
        shell: bash
        run: |
          changed_files=`python3 ${{ github.workspace }}/deploy/_filter_files.py yml ${{ steps.changed_files.outputs.changed_files }}`
          echo "Changed yaml files: $changed_files"
          echo "yaml_changed_files=$changed_files" >> $GITHUB_OUTPUT
      - name: Get changed json files
        id: changed_json_files
        shell: bash
        run: |
          cjf=`python3 ${{ github.workspace }}/deploy/_filter_files.py json ${{ steps.changed_files.outputs.changed_files }}`
          echo "Changed json files: $cjf"
          echo "json_changed_files=$cjf" >> $GITHUB_OUTPUT
