# Run tests
name: tests
run-name: Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: "Run Testing OS: ${{ matrix.os }} Python: ${{ matrix.python-version }}"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        exclude:
          - os: macos-latest
            python-version: "3.8"
          - os: macos-latest
            python-version: "3.9"
        include:
          - os: macos-13
            python-version: "3.8"
          - os: macos-13
            python-version: "3.9"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with retry
        uses: nick-invision/retry@7152eba30c6575329ac0576536151aca5a72780e
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            bash -c "pip install poetry pytest && \
                     poetry install --no-interaction --no-root -vvv --all-extras && \
                     poetry install --no-interaction --no-root --all-extras -vvv && \
                     pip install wheel && \
                     pip install --upgrade setuptools && \
                     pip install --editable '.[test,ml,medical,dev, ocv]'"

      - name: Run pytest
        shell: bash # Stops Windows hosts from using PowerShell
        run: |
          python -m pytest
