name: typecheck
run-name: Static analysis and typecheck

on:
  workflow_call:
    inputs:
      files:
        type: string
        description: "Files to lint"
        required: true

jobs:
  typecheck:
    if: ${{ inputs.files != '' }}
    runs-on: ubuntu-latest
    steps:
    - name: Check out source repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Show filenames
      run: echo ${{ inputs.files }}

    - name: MyPy typecheck
      shell: bash
      run: |
        pip install pydantic
        bash ${{ github.workspace }}/deploy/format_lint.sh typecheck ${{ inputs.files }}

