name: lint
run-name: Check linting

on:
  workflow_call:
    inputs:
      files:
        type: string
        description: "Files to lint"
        required: true

permissions:
  contents: read

jobs:
  lint:
    if: ${{ inputs.files != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit

    - name: Check out source repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Set up Python environment
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: "3.10"

    - name: Show filenames
      run: echo ${{ inputs.files }}

    - name: Ruff Lint
      shell: bash
      run: bash ${{ github.workspace }}/deploy/format_lint.sh lint ${{ inputs.files }}
