name: lint
run-name: Check linting

on:
  workflow_call:
    inputs:
      files:
        type: string
        description: "Files to lint"
        required: true

permissions:
  contents: read

jobs:
  lint:
    if: ${{ inputs.files != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - name: Check out source repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Python environment
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: "3.10"

    - name: Show filenames
      run: echo ${{ inputs.files }}

    - name: Ruff Lint
      shell: bash
      run: bash ${{ github.workspace }}/deploy/format_lint.sh lint ${{ inputs.files }}
