name: typecheck
run-name: Static analysis and typecheck

on:
  workflow_call:
    inputs:
      files:
        type: string
        description: "Files to lint"
        required: true

permissions:
  contents: read

jobs:
  typecheck:
    if: ${{ inputs.files != '' }}
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit

    - name: Check out source repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Python environment
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: "3.12"

    - name: Show filenames
      run: echo ${{ inputs.files }}

    - name: MyPy typecheck
      shell: bash
      run: |
        pip install pydantic
        bash ${{ github.workspace }}/deploy/format_lint.sh typecheck ${{ inputs.files }}
