name: generate-documentation
run-name: Generate Documentation

on:
  workflow_call:
    secrets:
      DARWIN_PY_AWS_GITHUB_CICD_ROLE:
        required: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  AWS_REGION: eu-west-1
  AWS_SESSION_NAME: darwinPyDocumentation

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Free Disk space
        shell: bash
        run: |
          sudo rm -rf /usr/local/lib/android  # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET

      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install poetry setuptools
          poetry install --all-extras --no-interaction --no-root
          pip install --editable ".[test,ml,medical,dev,ocv]"
          pip install -U sphinx sphinx_rtd_theme m2r2

      - name: Parse README
        run: |
          rm -f README.rst&&\
          m2r2 README.md&&\
          mv README.rst source/

      - name: Generate new docs
        env:
          PYTHONPATH: "."
        run: |
          rm -rf docs/*
          sphinx-apidoc -f -o source darwin darwin/future
          sphinx-build -b html source/ docs/
      - name: Setup access to AWS
        id: aws_assume_role
        uses: aws-actions/configure-aws-credentials@4fc4975a852c8cd99761e2de1f4ba73402e44dd9 # v4.0.3
        with:
          role-to-assume: ${{ secrets.DARWIN_PY_AWS_GITHUB_CICD_ROLE }}
          role-session-name: ${{ env.AWS_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload docs to S3
        run: aws s3 cp docs/ s3://darwin-py-sdk.v7labs.com/ --recursive
