name: lint
run-name: Check linting

on:
  workflow_call:
    inputs:
      files:
        type: string
        description: "Files to lint"
        required: true

permissions:
  contents: read

jobs:
  lint:
    if: ${{ inputs.files != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
      with:
        egress-policy: audit

    - name: Check out source repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Python environment
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: "3.12"

    - name: Show filenames
      run: echo ${{ inputs.files }}

    - name: Ruff Lint
      shell: bash
      run: bash ${{ github.workspace }}/deploy/format_lint.sh lint ${{ inputs.files }}
