name: Python package

on: [push]

jobs:
  upload-s3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: '.'
          destination_dir: ''

